# Generated by Django 3.2 on 2023-08-12 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'kategori',
            },
        ),
        migrations.CreateModel(
            name='BarangMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pc', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('vga', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serialnumber', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gudang.kategori')),
            ],
            options={
                'verbose_name_plural': 'barang masuk',
            },
        ),
    ]
