# Generated by Django 3.2 on 2023-08-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangmasuk',
            options={},
        ),
    ]
