# Generated by Django 3.2 on 2023-08-13 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0002_alter_barangmasuk_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangmasuk',
            options={'verbose_name_plural': 'barang masuk'},
        ),
    ]
