# Generated by Django 3.2 on 2023-08-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0004_auto_20230813_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.TextField(max_length=100)),
                ('user', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('pc', models.TextField(max_length=100)),
                ('os', models.TextField(max_length=100)),
                ('cpu', models.TextField(max_length=100)),
                ('vga', models.TextField(max_length=100)),
                ('ram', models.TextField(max_length=100)),
                ('model', models.TextField(max_length=100)),
                ('serialnumber', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gudang.kategori')),
            ],
            options={
                'verbose_name_plural': 'barang keluar',
            },
        ),
    ]
