# Generated by Django 4.2.4 on 2023-08-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gudang", "0007_alter_barangmasuk_kategori"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barangmasuk",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
