# Generated by Django 4.2.4 on 2023-08-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gudang", "0010_alter_barangmasuk_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barangkeluar",
            name="date",
        ),
        migrations.AddField(
            model_name="barangkeluar",
            name="date_keluar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="barangkeluar",
            name="date_masuk",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
