# Generated by Django 3.2 on 2023-08-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0012_auto_20230820_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
