# Generated by Django 4.2.4 on 2023-09-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gudang", "0013_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lokasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lokasi", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "lokasi",
            },
        ),
    ]
