# Generated by Django 4.2.4 on 2023-09-08 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gudang", "0014_lokasi"),
    ]

    operations = [
        migrations.AddField(
            model_name="barangkeluar",
            name="lokasi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gudang.lokasi",
            ),
        ),
        migrations.AddField(
            model_name="barangmasuk",
            name="lokasi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gudang.lokasi",
            ),
        ),
    ]
